
package service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.13
 * Sun Mar 05 22:59:28 WAT 2023
 * Generated source version: 2.7.13
 */

@XmlRootElement(name = "addCamion", namespace = "http://service/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addCamion", namespace = "http://service/")

public class AddCamion {

    @XmlElement(name = "arg0")
    private model.Camion arg0;

    public model.Camion getArg0() {
        return this.arg0;
    }

    public void setArg0(model.Camion newArg0)  {
        this.arg0 = newArg0;
    }

}

