
package service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.13
 * Sun Mar 05 22:59:28 WAT 2023
 * Generated source version: 2.7.13
 */

@XmlRootElement(name = "updateCamionById", namespace = "http://service/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateCamionById", namespace = "http://service/", propOrder = {"arg0", "arg1"})

public class UpdateCamionById {

    @XmlElement(name = "arg0")
    private int arg0;
    @XmlElement(name = "arg1")
    private model.Camion arg1;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

    public model.Camion getArg1() {
        return this.arg1;
    }

    public void setArg1(model.Camion newArg1)  {
        this.arg1 = newArg1;
    }

}

