
package service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.13
 * Sun Mar 05 22:59:28 WAT 2023
 * Generated source version: 2.7.13
 */

@XmlRootElement(name = "updateCamionByIdResponse", namespace = "http://service/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateCamionByIdResponse", namespace = "http://service/")

public class UpdateCamionByIdResponse {


}

